"use client";

import { useEffect, useRef, useState } from "react";
import type { BuilderConfig, PlinthSize } from "@/lib/config";
import LiveSetupPreview from "./LiveSetupPreview";

// Keep in sync with app/api/generate/route.ts PLINTH_MODE.
// "ai" = plinths sent to AI prompt, SVG overlay hidden.
// "svg" = plinths rendered as CSS overlay, not in AI prompt.
const PLINTH_MODE: "ai" | "svg" = "ai";

export type PreviewStatus = "idle" | "loading" | "done" | "error";

/** Derive the prompt's extra ids from the current decor selections. */
export function deriveExtras(config: BuilderConfig): string[] {
  const e: string[] = [];
  if (config.decor.cakeTable) e.push("dessert_table");
  return e;
}

/** Height of each plinth as % of the image container height. */
const PLINTH_HEIGHT_PCT: Record<PlinthSize, number> = {
  small: 22,
  medium: 25,
  large: 28,
};

/** Horizontal center positions (% from left) for 1, 2, or 3 plinths. */
const PLINTH_X_PCT: Record<number, number[]> = {
  1: [50],
  2: [35, 65],
  3: [25, 50, 75],
};

/**
 * SVG plinth overlay rendered on top of the AI image.
 * Plinths are shown as narrow white rounded rectangles sitting on the
 * bottom edge of the preview — not generated by the AI.
 */
function PlinthOverlay({ sizes }: { sizes: PlinthSize[] }) {
  const n = Math.min(3, sizes.length);
  if (n === 0) return null;
  const xPositions = PLINTH_X_PCT[n] ?? [50];

  return (
    <div className="pointer-events-none absolute inset-0">
      {sizes.slice(0, 3).map((size, i) => {
        const left = xPositions[i] ?? 50;
        const h = PLINTH_HEIGHT_PCT[size] ?? 25;
        return (
          <div
            key={i}
            style={{
              position: "absolute",
              bottom: "5%",
              left: `${left}%`,
              transform: "translateX(-50%)",
              width: "6%",
              height: `${h}%`,
              background: "#FFFFFF",
              borderRadius: "4px",
              boxShadow:
                "2px 2px 8px rgba(0,0,0,0.25), inset -2px 0 4px rgba(0,0,0,0.08)",
            }}
          />
        );
      })}
    </div>
  );
}

/**
 * Debounced auto-generation of the photorealistic preview. Fires 1.5s after the
 * last change to theme / package / backdrop shape / balloon style / extras.
 * Stale responses are discarded via a request-id guard.
 * Plinth changes do NOT retrigger generation — plinths are rendered as an overlay.
 */
export function useSetupPreview(config: BuilderConfig) {
  const [status, setStatus] = useState<PreviewStatus>("idle");
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const reqId = useRef(0);
  const [nonce, setNonce] = useState(0); // bumped by regenerate()

  const extras = deriveExtras(config);
  const d = config.decor;
  // Plinths included in sig only in AI mode (they affect the generated image).
  const sig = JSON.stringify({
    t: config.theme,
    p: config.package,
    cnt: d.backdropCount,
    s: d.backdropShape,
    b: d.balloonStyle,
    bc: d.backdropColor,
    blc: d.balloonColors,
    txt: d.backdropText,
    bp: d.backdropPrint,
    cut: d.cutouts,
    pl: PLINTH_MODE === "ai" ? d.plinthSizes : undefined,
    e: extras,
    n: nonce,
  });

  useEffect(() => {
    const id = ++reqId.current;
    setStatus("loading");
    const timer = setTimeout(async () => {
      try {
        const res = await fetch("/api/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            theme: config.theme,
            package: config.package,
            backdropCount: d.backdropCount,
            backdropShape: d.backdropShape,
            backdropColor: d.backdropColor,
            balloonStyle: d.balloonStyle,
            balloonColors: d.balloonColors,
            backdropText: d.backdropText,
            backdropPrint: d.backdropPrint,
            cutouts: d.cutouts,
            plinthSizes: PLINTH_MODE === "ai" ? d.plinthSizes : undefined,
            extras,
          }),
        });
        const data = await res.json().catch(() => ({}));
        if (id !== reqId.current) return; // superseded by a newer request
        if (!res.ok || !data.imageUrl) {
          setStatus("error");
          return;
        }
        setImageUrl(data.imageUrl);
        setStatus("done");
      } catch {
        if (id === reqId.current) setStatus("error");
      }
    }, 1500);

    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sig]);

  return {
    status,
    imageUrl,
    regenerate: () => setNonce((n) => n + 1),
  };
}

export default function SetupPreview({
  config,
  status,
  imageUrl,
  onRegenerate,
  showControls = true,
}: {
  config: BuilderConfig;
  status: PreviewStatus;
  imageUrl: string | null;
  onRegenerate: () => void;
  showControls?: boolean;
}) {
  const hasImage = status === "done" && !!imageUrl;

  return (
    <div>
      <div className="relative aspect-[4/3] w-full overflow-hidden rounded-2xl shadow-inner">
        {/* AI image when ready, otherwise the canvas sketch as fallback */}
        {hasImage ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={imageUrl!}
            alt="AI-generated party setup preview"
            className="h-full w-full object-cover"
          />
        ) : (
          <LiveSetupPreview config={config} />
        )}

        {/* Plinth overlay — SVG mode only; AI mode renders plinths in the image */}
        {hasImage && PLINTH_MODE === "svg" && (
          <PlinthOverlay sizes={config.decor.plinthSizes} />
        )}

        {/* Loading skeleton with shimmer */}
        {status === "loading" && (
          <div className="shimmer absolute inset-0 flex flex-col items-center justify-center gap-3 bg-accent-soft/80 backdrop-blur-sm">
            <div className="h-9 w-9 animate-spin rounded-full border-4 border-accent/25 border-t-accent" />
            <span className="text-sm font-medium text-accent">Creating your preview…</span>
          </div>
        )}

        {/* Regenerate button (corner) */}
        {showControls && hasImage && (
          <button
            type="button"
            onClick={onRegenerate}
            className="absolute right-2 top-2 flex items-center gap-1 rounded-full bg-black/55 px-3 py-1.5 text-[11px] font-medium text-white backdrop-blur transition hover:bg-black/70"
          >
            <span className="text-sm leading-none">↻</span> Regenerate
          </button>
        )}

        {/* Fallback note when generation failed */}
        {status === "error" && (
          <div className="absolute inset-x-0 bottom-0 flex items-center justify-between gap-2 bg-black/45 px-3 py-1.5 backdrop-blur">
            <span className="text-[11px] text-white">
              AI preview unavailable — showing sketch
            </span>
            {showControls && (
              <button
                type="button"
                onClick={onRegenerate}
                className="rounded-full bg-white/20 px-2 py-0.5 text-[11px] font-medium text-white"
              >
                Retry
              </button>
            )}
          </div>
        )}
      </div>

      <p className="mt-2 text-center text-[11px] text-black/45">
        AI preview — actual setup may vary slightly
      </p>
    </div>
  );
}
